### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by jeffmelville** [dmolin/flightSimPanels#12]
What is the license for this code? I would be interested in leveraging it somewhere but cannot if it is GPL or has unclear licensing terms.

**Comment by dmolin** [comment]
Hey jeff, the absence of a licence file means that this project is protected by copyright (All Right Reserved). It's my intention to add a licence file though and to make it usable and modifiable but only for non-commercial purposes (so, no derivative work of commercial nature). If your intention is to use this code for non-commercial purposes feel free to fork it and use it :)

**Comment by jeffmelville** [comment]
OK thanks. The reason I asked was that I couldn't even find so much as a copyright notice anywhere in the code (in a few files I looked at). Given that the code is on github some people might erroneously consider it to be in the public domain in absence of anything else.

My use case is a little gray. I'm evaluating tools that could be included in a closed source codebase that's owned by a non-profit but COULD receive a licensing fee at some point. Respecting the spirit of what you said probably excludes me from using it. Thanks anyway for your response.

**Comment by dmolin** [comment]
This project is now GPLv3 :)
