### ISSUE TITLE
Design for Altimeter

### ISSUE THREAD

**Issue by mcongrove** [dmolin/flightSimPanels#6]
You want me to do this for you while you work on the code, or have you already started?

**Comment by dmolin** [comment]
There's a PSD already started under client/images; as you can see, it's just the starting point; You're free to pick it up and go on with it as you please if you want :)

**Comment by mcongrove** [comment]
Hmm, don't see the `client` directory in the `master` branch.

**Comment by dmolin** [comment]
uh. let me double check...

**Comment by dmolin** [comment]
..aaaaand you're right! LOL, committed :D

**Comment by mcongrove** [comment]
There we go :) I'll take it from here. I've gotten pretty quick and doing these things now.

You plan on including the atmospheric pressure setting?

**Comment by dmolin** [comment]
yep, I already send them to the client as an object (  { pressures: { baro:'', mbar:'' }  } )
